### ISSUE TITLE
Don't add obviously unnecessary steps

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dtplyr#254]
It would be a bit nicer to not add a step when it is obviously not necessary.

empty dots -> nothing to do
* [x] `arrange()`
* [x] `filter()`: in #255
* [x] `mutate()`: in #247
* [x] `relocate()`: in #240
* [x] `rename()`, `rename_with()`: since #241

can easily analyse if anything changes:
* [x] `relocate()`: in #240
* [x] `rename()`, `rename_with()`: since #241
* [x] `select()`: in #255
* [x] `group_by()`, `ungroup()`: in #255
* [x] `slice()`

Not obvious way when to skip steps
* `count()`, `tally()`, `add_count()`, `add_tally()`: number of rows
* `distinct()`: use all variables
* `summarise()`
* `transmute()`
* `slice_*()`
